package com.model.pojo;
// Generated Sep 11, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name="document"
    ,schema="public"
)
public class Document  implements java.io.Serializable {


     private int id;
     private String code;
     private Date date;
     private String name;
     private Set documentitems = new HashSet(0);

    public Document() {
    }

	
    public Document(int id) {
        this.id = id;
    }
    public Document(int id, String code, Date date, String name, Set documentitems) {
       this.id = id;
       this.code = code;
       this.date = date;
       this.name = name;
       this.documentitems = documentitems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="code")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="document", orphanRemoval = true, cascade = CascadeType.PERSIST)
    public Set getDocumentitems() {
        return this.documentitems;
    }
    
    public void setDocumentitems(Set documentitems) {
        this.documentitems = documentitems;
    }
   
}


