package com.model.pojo;
// Generated Sep 11, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentitem generated by hbm2java
 */
@Entity
@Table(name="documentitem"
    ,schema="public"
)
public class Documentitem  implements java.io.Serializable {


     private int id;
     private Document document;
     private String name;
     private Double price;

    public Documentitem() {
    }

	
    public Documentitem(int id) {
        this.id = id;
    }
    public Documentitem(int id, Document document, String name, Double price) {
       this.id = id;
       this.document = document;
       this.name = name;
       this.price = price;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="documentid")
    public Document getDocument() {
        return this.document;
    }
    
    public void setDocument(Document document) {
        this.document = document;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price", scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


